spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgresSQLDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgres"
    name: springDatasource
    platform: postgresql
    driver-class-name: org.postgresql.Driver